apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "order-service.name" . }}-properties
data:
  application.properties: |
    server.servlet.contextPath = /order-service
    spring.jackson.date-format = yyyy-MM-dd
    spring.application-name = order-service
    payment.service.api.url = {{ .Values.paymentservice.api.url}}