logging:
  level:
    root: INFO

server:
   servlet:
      contextPath: /order-service
spring:
   jmx:
      enabled: true
   application:
      name: order-service
   jackson:
      date-format: yyyy-MM-dd
   datasource:
      url: jdbc:h2:mem:testdb
      driverClassName: org.h2.Driver
   jpa:
      database-platform: org.hibernate.dialect.H2Dialect
   h2:
      console:
         enabled: true
   cloud:
      gcp:
         trace:
            enabled: false
            project-id: project-us-350-08
   sleuth:
      sampler:
         probability: 1
      web:
         skipPattern: (^cleanup.*|.+favicon.*)
   zipkin.service.name: order-service
payment.service.api.url: http://localhost:8070/payment-service/api/v1

opentracing:
  jaeger:
    enabled: true
    udp-sender:
      host: localhost
      port: 6831
    service-name: order-service

management.trace.http.enabled: true
management.endpoints.web.exposure.include: "*,httptrace,prometheus,bindings,streamsbindings"
management.endpoint.health.show-details: always