logging:
  level:
    root: INFO

server:
   servlet:
      contextPath: /order-service
spring:
   jmx:
      enabled: false
   application:
      name: order-service
   jackson:
      date-format: yyyy-MM-dd
   datasource:
      url: jdbc:h2:mem:testdb
      driverClassName: org.h2.Driver
   jpa:
      database-platform: org.hibernate.dialect.H2Dialect
   h2:
      console:
         enabled: true

payment.service.api.url: http://localhost:8070/payment-service/api/v1

management:
   trace:
      http:
         enabled: true
   endpoints:
      web:
         base-path : "/order-service/actuator"      
         exposure:
            include: "*,httptrace,prometheus,bindings,streamsbindings"
      health:
         show-details: always
   server:
      port: 8066