apiVersion: v1
kind: Service
metadata:
  name: {{ include "order-service.name" . }}
spec:
  selector:
    app: {{ include "order-service.name" . }}
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  type: LoadBalancer      
  externalIPs:
  - 192.168.99.106
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "order-service.name" . }}-properties
data:
  application.properties: |
    server.servlet.contextPath = /order-service
    spring.jackson.date-format = yyyy-MM-dd
    spring.application-name = order-service
    payment.service.api.url = http://payment-service.default.svc.cluster.local:8080/payment-service/api/v1