apiVersion: v1
kind: ConfigMap
metadata:
  name: order-service-properties
data:
  application.properties: |
    server.servlet.contextPath = /order-service
    spring.jackson.date-format = yyyy-MM-dd
    spring.application-name = order-service
    payment.service.api.url = http://payment-service.default.svc.cluster.local:8080/payment-service/api/v1
