openapi: 3.0.1
info:
   title: Order Service - REST API
   description: Order - REST API
   version: 1.0.0
   contact: {}
servers:
-  url: http://localhost:8080/api/v1
paths:
#### orders ####
   /orders:
      post:
         operationId: create
         responses:
            '201':
               description: Order list
               content:
                  application/json:
                     schema:
                        $ref: '#/components/schemas/NewOrder'
            '400':
               description: Bad request
               content:
                  application/json:
                     schema:
                        $ref: '#/components/schemas/Error'
            '500':
               description: Server error
               content:
                  application/json:
                     schema:
                        $ref: '#/components/schemas/Error'
            '401':
               description: Not Authenticated
               content:
                  application/json:
                     schema:
                        $ref: '#/components/schemas/Error'
         tags:
         - order
      get:
         operationId: getList
         responses:
            '200':
               description: Order list
               content:
                  application/json:
                     schema:
                        type: array
                        items:
                           $ref: '#/components/schemas/Order'
            '400':
               description: Bad request
               content:
                  application/json:
                     schema:
                        $ref: '#/components/schemas/Error'
            '500':
               description: Server error
               content:
                  application/json:
                     schema:
                        $ref: '#/components/schemas/Error'
            '401':
               description: Not Authenticated
               content:
                  application/json:
                     schema:
                        $ref: '#/components/schemas/Error'
         tags:
         - order
   /orders/{id}:
      get:
         operationId: getById
         parameters:
         -  name: id
            in: path
            required: true
            schema:
               type: string
               format: uuid
         responses:
            '200':
               description: Order found
               content:
                  application/json:
                     schema:
                        $ref: '#/components/schemas/Order'
            '404':
               description: Order not found
               content:
                  application/json:
                     schema:
                        $ref: '#/components/schemas/Error'
            '500':
               description: Server error
               content:
                  application/json:
                     schema:
                        $ref: '#/components/schemas/Error'
            '401':
               description: Not Authenticated
               content:
                  application/json:
                     schema:
                        $ref: '#/components/schemas/Error'
         tags:
         - order
      delete:
         operationId: delete
         parameters:
         -  name: id
            in: path
            required: true
            schema:
               type: string
               format: uuid
         responses:
            '204':
               description: Order deleted
            '404':
               description: Order not found
               content:
                  application/json:
                     schema:
                        $ref: '#/components/schemas/Error'
            '500':
               description: Server error
               content:
                  application/json:
                     schema:
                        $ref: '#/components/schemas/Error'
            '401':
               description: Not Authenticated
               content:
                  application/json:
                     schema:
                        $ref: '#/components/schemas/Error'
         tags:
         - order
components:
   links: {}
   callbacks: {}
   schemas:
      Order:
         type: object
         properties:
            id:
               type: string
               format: uuid
            create_date:
               type: string
               format: date
            total:
               type: number
               format: double
               example: 100.0
            status:
               type: string
               example: pending
         required:
         - id
         - create_date
         - status
      NewOrder:
         type: object
         properties:
            id:
               type: string
               format: uuid
         required:
         - id
      Error:
         type: object
         properties:
            code:
               type: string
            message:
               type: string
         required:
         - codice
tags:
-  name: order